@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.example.task5.Aggregate",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1322970774 { 
   	label=example
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_129515980 { 
   	label=task5
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   Aggregate537999329[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)Aggregate</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getIterator(): Iterator</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

BuilderTextProperty537999329[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)BuilderTextProperty</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   conaggr: ConcreteAggregate [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   indicator: Indicator [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   iter: Iterator [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   text: Label [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   time: Timeline [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ ImageScroll(image: Image)</TD></TR>
<TR><TD ALIGN="LEFT" >+ TextAnimation(button: boolean)</TD></TR>
<TR><TD ALIGN="LEFT" >+ addText(text: String, textSize: int, textColor: Color)</TD></TR>
<TR><TD ALIGN="LEFT" >+ build(): Indicator</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ConcreteAggregate537999329[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ConcreteAggregate</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   bi: Image [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   filetopic: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

HelloController537999329[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)HelloController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   auto: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   builder: BuilderTextProperty [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   color: ColorPicker [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   conaggr: ConcreteAggregate [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   director: Director [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   indicator: Indicator [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   initialValue: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   iter: Iterator [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   label: Label [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   panee: BorderPane [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   spinner: Spinner&lt;Integer&gt; [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   textField: TextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   time: Timeline [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   valueFactory: SpinnerValueFactory&lt;Integer&gt; [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   vbox: VBox [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ initialize()</TD></TR>
<TR><TD ALIGN="LEFT" >+ onBack()</TD></TR>
<TR><TD ALIGN="LEFT" >+ onClear()</TD></TR>
<TR><TD ALIGN="LEFT" >+ onForward()</TD></TR>
<TR><TD ALIGN="LEFT" >+ onPause()</TD></TR>
<TR><TD ALIGN="LEFT" >+ onPlay()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
Aggregate537999329 -> ConcreteAggregate537999329[arrowhead=none, arrowtail=empty, dir=both];
BuilderTextProperty537999329 -> ConcreteAggregate537999329[label="conaggr
[0..1]"];
HelloController537999329 -> BuilderTextProperty537999329[label="builder
[0..1]"];
HelloController537999329 -> ConcreteAggregate537999329[label="conaggr
[0..1]"];
    
}
@enduml